runtime: go120
service: prospero_searcher
port: 5000
is_debug: true
use_cron_sources_rss: false
cron_sources_rss: "*/1 * * * *"
#cron_sources_rss: "0 * * * *"
migrate: true
tracing: false
metrics: false
logger:
    to_file: true
    to_console: true
    to_elk: false
    use_zap: true
    use_default_gin: true
#    use_logrus: false
#    to_graylog: false
#    is_Json: true
#    graylog_addr: localhost:12201
