runtime: go120
service: prospero_searcher
port: 5000
#cron_sources_rss: "*/1 * * * *"
cron_sources_rss: "*/5 * * * *"
use_cron_sources_rss: false
use_tracing_jaeger: true
migrate_postgres: true
migrate_elastic: true
metrics: true
logger:
    to_file: true
    to_console: true
    to_elk: true
    use_zap: true
    use_default_gin: false
#    use_logrus: false
#    to_graylog: false
#    is_Json: true
#    graylog_addr: localhost:12201
