version: '3.9'
services:
  # ----------------------------------- APPS
  # Prospero
  prospero:
    build: .
    volumes:
      - ./logs/:/logs/
      - prospero:/app/logs
    ports:
      - "5000:5000"
    networks:
      - prospero
  # ----------------------------------- METRICS
  # Prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prospero
  # Grafana
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - prospero
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=mskKote
    volumes:
      - ./resources/grafana.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana:/var/lib/grafana
  # ----------------------------------- LOGGER
  # ElasticSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
#    volumes:
#      - ./resources/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health" ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "9200:9200"
    networks:
      - prospero
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    volumes:
      - ./resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - prospero
  # Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.1
    entrypoint: filebeat -e -strict.perms=false
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./resources/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/
      - prospero:/app/logs
    networks:
      - prospero
  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://localhost:5601/api/status" ]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - "5601:5601"
    networks:
      - prospero
  # ----------------------------------- TRACING
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - prospero
    ports:
      - "16686:16686"
      - "14269:14269"
      - "14268:14268"

# ----------------------------------- OTHER
networks:
  prospero:
    driver: bridge
# Persistent data stores https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  grafana:
  elasticsearch:
  kibana:
  prospero:


# MongoDB: https://hub.docker.com/_/mongo/
  #  mongo:
  #    image: mongo:5.0.13
  #    networks:
  #      - prospero
  # ElasticSearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  #  elasticsearch_graylog:
  #    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
  #    environment:
  #      - http.host=0.0.0.0
  #      - transport.host=localhost
  #      - network.host=0.0.0.0
  ##      - xpack.security.enabled=false
  #      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  #    ulimits:
  #      memlock:
  #        soft: -1
  #        hard: -1
  #    deploy:
  #      resources:
  #        limits:
  #          memory: 1g
  #    networks:
  #      - prospero
  # Graylog: https://hub.docker.com/r/graylog/graylog/
#  graylog:
#    image: graylog/graylog:5.0
#    environment:
#      # CHANGE ME (must be at least 16 characters)!
#      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
#      # Password: admin
#      - GRAYLOG_ROOT_PASSWORD_SHA2=e2bef020851ae9af8f2e1d0dd51b782dd22483700d389512dcebd366d6deebbc
#      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
#    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
#    networks:
#      - prospero
#    restart: always
#    depends_on:
#      - mongo
#      - elasticsearch_graylog
#    ports:
#      # Graylog web interface and REST API
#      - "9000:9000"
#      # Syslog TCP
#      - "1514:1514"
#      # Syslog UDP
#      - "1514:1514/udp"
#      # GELF TCP
##      - "12201:12201"
#      # GELF UDP
#      - "12201:12201/udp"
#      # Log Input TCP
#      - "5555:5555"
