apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms2048m -Xmx3072m
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: "false"
            - name: discovery.type
              value: single-node
            - name: network.host
              value: 0.0.0.0
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.enrollment.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
          livenessProbe:
            exec:
              command:
                - curl
                - -s
                - -f
                - http://localhost:9200/_cat/health
            failureThreshold: 20
            periodSeconds: 3
            timeoutSeconds: 3
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              name: elasticsearch-cm0
              readOnly: true
              subPath: elasticsearch.yml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
            name: elasticsearch-cm0
          name: elasticsearch-cm0
