apiVersion: v1
data:
  elasticsearch.yml: |-
    discovery.type: single-node
    network.host: 0.0.0.0
    cluster.routing.allocation.disk.threshold_enabled: false
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch-cm0
