apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: filebeat
  name: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filebeat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: filebeat
    spec:
      containers:
        - command:
            - filebeat
            - -e
            - -strict.perms=false
          image: docker.elastic.co/beats/filebeat:8.7.1
          name: filebeat
          volumeMounts:
            - mountPath: /usr/share/filebeat/filebeat.yml
              name: filebeat-cm0
              subPath: filebeat.yml
            - mountPath: /logs
              name: filebeat-claim1
            - mountPath: /app/logs
              name: prospero
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: filebeat.yml
                path: filebeat.yml
            name: filebeat-cm0
          name: filebeat-cm0
        - name: filebeat-claim1
          persistentVolumeClaim:
            claimName: filebeat-claim1
        - name: prospero
          persistentVolumeClaim:
            claimName: prospero
