apiVersion: v1
data:
  grafana.yml: |-
    ---
    apiVersion: 1
    datasources:
      - name: Main
        type: prometheus
        url: http://prometheus:9090
        isDefault: true
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: grafana
  name: grafana-cm0
