apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "14269"
      port: 14269
      targetPort: 14269
    - name: "14268"
      port: 14268
      targetPort: 14268
  selector:
    io.kompose.service: jaeger
