apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: kibana
    spec:
      containers:
        - image: docker.elastic.co/kibana/kibana:8.7.1
          livenessProbe:
            exec:
              command:
                - curl
                - -s
                - -f
                - http://localhost:5601/api/status
            failureThreshold: 50
            periodSeconds: 3
            timeoutSeconds: 3
          name: kibana
          ports:
            - containerPort: 5601
              protocol: TCP
      restartPolicy: Always
