apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - image: docker.elastic.co/logstash/logstash:8.7.1
          name: logstash
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: logstash-cm0
              readOnly: true
              subPath: logstash.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: logstash.conf
                path: logstash.conf
            name: logstash-cm0
          name: logstash-cm0
