apiVersion: v1
data:
  prometheus.yml: |
    ---
    global:
      scrape_interval: 60s
      evaluation_interval: 60s

    alerting:

    rule_files:

    scrape_configs:
      - job_name: prospero
        static_configs:
          - targets: ["prospero:80"]
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
