apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: prospero
  name: prospero
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
