apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: prospero
  name: prospero
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prospero
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: prospero
    spec:
      containers:
        - env:
            - name: ADMINKA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: ADMINKA_PASSWORD
                  name: env-production
            - name: ADMINKA_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: ADMINKA_USERNAME
                  name: env-production
            - name: ELASTIC_CON_STR
              valueFrom:
                configMapKeyRef:
                  key: ELASTIC_CON_STR
                  name: env-production
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: env-production
            - name: JAEGER_HOST
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_HOST
                  name: env-production
            - name: JAEGER_PORT
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_PORT
                  name: env-production
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET_KEY
                  name: env-production
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DATABASE
                  name: env-production
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env-production
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-production
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env-production
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USERNAME
                  name: env-production
          image: prospero
          livenessProbe:
            exec:
              command:
                - wget
                - -q
                - --spider
                - http://localhost:80/service/healthcheck
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 3
            timeoutSeconds: 3
          name: prospero
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /logs
              name: prospero-claim0
            - mountPath: /app/logs
              name: prospero
      restartPolicy: Always
      volumes:
        - name: prospero-claim0
          persistentVolumeClaim:
            claimName: prospero-claim0
        - name: prospero
          persistentVolumeClaim:
            claimName: prospero
