name: Deploy self-hosted (Prospero without infra)

on:
  push:
    branches: [ "main", "release" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Stop & Remove containers, networks
        run: docker-compose rm -f prospero
      - name: Remove unused data
        run: docker system prune prospero_backend-prospero -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: docker-compose
        run: docker-compose up -d